# Generated by Django 4.2.3 on 2023-07-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichas_tecnicas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pdf', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='lineas_investigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='medidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='objetivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='iq_fiscalizados',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('formula', models.CharField(max_length=50)),
                ('imagen_iqf', models.BinaryField()),
                ('fecha_v_antigua', models.DateTimeField()),
                ('fecha_v_reciente', models.DateTimeField()),
                ('fichas_tecnicas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iqf_app.fichas_tecnicas')),
                ('inventarios', models.ManyToManyField(to='iqf_app.inventarios')),
                ('lineas_investigacion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iqf_app.lineas_investigacion')),
                ('medidas_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iqf_app.medidas')),
                ('objetivos', models.ManyToManyField(to='iqf_app.objetivos')),
            ],
        ),
    ]
