# Generated by Django 4.2.3 on 2023-07-16 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0002_fichas_tecnicas_lineas_investigacion_medidas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='denominaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conjunto', models.CharField(max_length=400)),
                ('iq_fiscalizados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados')),
            ],
        ),
    ]
