# Generated by Django 4.2.3 on 2023-07-17 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0003_denominaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarios',
            name='cantidad',
        ),
        migrations.CreateModel(
            name='iq_fiscalizados_objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq_fiscalizados_id', models.ForeignKey(db_column='iq_fiscalizado_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados')),
                ('objetivos_id', models.ForeignKey(db_column='objetivos_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.objetivos')),
            ],
        ),
        migrations.CreateModel(
            name='iq_fiscalizados_inventarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('inventarios_id', models.ForeignKey(db_column='inventarios_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.inventarios')),
                ('iq_fiscalizados_id', models.ForeignKey(db_column='iq_fiscalizado_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados')),
            ],
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados',
            name='inventarios',
            field=models.ManyToManyField(through='iqf_app.iq_fiscalizados_inventarios', to='iqf_app.inventarios'),
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados',
            name='objetivos',
            field=models.ManyToManyField(through='iqf_app.iq_fiscalizados_objetivos', to='iqf_app.objetivos'),
        ),
    ]
