# Generated by Django 4.2.3 on 2023-07-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0005_alter_iq_fiscalizados_inventarios_inventarios_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iq_fiscalizados_inventarios',
            name='inventarios_id',
            field=models.ForeignKey(db_column='inventarios_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.inventarios'),
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados_inventarios',
            name='iq_fiscalizados_id',
            field=models.ForeignKey(db_column='iq_fiscalizados_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados'),
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados_objetivos',
            name='iq_fiscalizados_id',
            field=models.ForeignKey(db_column='iq_fiscalizados_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados'),
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados_objetivos',
            name='objetivos_id',
            field=models.ForeignKey(db_column='objetivos_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.objetivos'),
        ),
    ]
