# Generated by Django 4.2.3 on 2023-07-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0007_auto_20230716_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='titulos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
    ]
