# Generated by Django 4.2.3 on 2023-07-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0008_titulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichas_tecnicas',
            name='nombre_pdf',
            field=models.FileField(upload_to='fichas_t/'),
        ),
        migrations.AlterField(
            model_name='iq_fiscalizados',
            name='imagen_iqf',
            field=models.ImageField(blank=True, null=True, upload_to='iqf'),
        ),
    ]
