# Generated by Django 4.2.3 on 2023-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0009_alter_fichas_tecnicas_nombre_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='noti_estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
