# Generated by Django 4.2.3 on 2023-07-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iqf_app', '0010_noti_estados'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificaciones_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('solicitud', models.FileField(upload_to='solicitudes/')),
                ('fecha_envio', models.DateTimeField()),
                ('emisor_id', models.ForeignKey(db_column='emisor_id', on_delete=django.db.models.deletion.CASCADE, related_name='emisor_id', to=settings.AUTH_USER_MODEL)),
                ('noti_estados_id', models.ForeignKey(db_column='noti_estados_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.noti_estados')),
                ('receptor_id', models.ForeignKey(db_column='receptor_id', on_delete=django.db.models.deletion.CASCADE, related_name='receptor_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
