# Generated by Django 4.2.3 on 2023-07-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0013_iq_fiscalizados_notificaciones_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones_user',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
