# Generated by Django 4.2.3 on 2023-07-26 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0014_notificaciones_user_fecha_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iq_fiscalizados',
            name='lineas_investigacion_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iqf_app.lineas_investigacion'),
        ),
    ]
