# Generated by Django 4.2.3 on 2023-07-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0015_alter_iq_fiscalizados_lineas_investigacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iq_fiscalizados',
            name='lineas_investigacion_id',
        ),
        migrations.CreateModel(
            name='iq_fiscalizados_lineas_investigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq_fiscalizados_id', models.ForeignKey(db_column='iq_fiscalizados_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados')),
                ('lineas_investigacion_id', models.ForeignKey(db_column='lineas_investigacion_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.lineas_investigacion')),
            ],
        ),
        migrations.AddField(
            model_name='iq_fiscalizados',
            name='lineas_investigacion',
            field=models.ManyToManyField(blank=True, null=True, through='iqf_app.iq_fiscalizados_lineas_investigacion', to='iqf_app.lineas_investigacion'),
        ),
    ]
