# Generated by Django 4.2.3 on 2023-07-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0016_remove_iq_fiscalizados_lineas_investigacion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iq_fiscalizados',
            name='lineas_investigacion',
            field=models.ManyToManyField(blank=True, through='iqf_app.iq_fiscalizados_lineas_investigacion', to='iqf_app.lineas_investigacion'),
        ),
    ]
