# Generated by Django 4.2.3 on 2023-07-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0018_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_usuario',
            name='titulo',
        ),
    ]
