# Generated by Django 4.2.3 on 2023-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0020_perfil_usuario_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciones_user',
            name='nro_oficio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
