# Generated by Django 4.2.3 on 2023-07-27 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0023_iq_fiscalizados_pecosas_pecosas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_articulo', models.CharField(blank=True, max_length=60, null=True)),
                ('concentracion', models.FloatField(blank=True, null=True)),
                ('fecha_v', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='iq_fiscalizados_marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq_fiscalizados_id', models.ForeignKey(db_column='iq_fiscalizados_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.iq_fiscalizados')),
                ('marcas_id', models.ForeignKey(db_column='marcas_id', on_delete=django.db.models.deletion.CASCADE, to='iqf_app.marcas')),
            ],
        ),
        migrations.AddField(
            model_name='iq_fiscalizados',
            name='marcas',
            field=models.ManyToManyField(through='iqf_app.iq_fiscalizados_marcas', to='iqf_app.marcas'),
        ),
    ]
