# Generated by Django 4.2.3 on 2023-07-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0024_marcas_iq_fiscalizados_marcas_iq_fiscalizados_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcas',
            name='nombre',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
