# Generated by Django 4.2.3 on 2023-07-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0025_marcas_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='nombres_marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
