# Generated by Django 4.2.3 on 2023-07-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iqf_app', '0026_nombres_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones_user',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='iq_fiscalizados_notificaciones_user',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
